version: '3.9'

services:
  db:
    image: mysql
    container_name: cloud_db

    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: cloud
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: students_db
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/